<?php
include_once("app/test/curl.php");
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-03-15 at 10:49:28.
 */
class sessionsTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Hello
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testFailingPost()
	{
		$url = "http://localhost/portfolio/sessions/";

		$array = array("id"=>"fail","password"=>"fail","persistent"=>"");
		$postfields = http_build_query($array);
		$status = curl_post($url,$postfields);
		$this->assertEquals('401', $status);
		//return $return;
	}
	public function testPost()
	{
		$url = "http://localhost/portfolio/sessions/";

		$array = array("id"=>"test","password"=>"test","persistent"=>"");
		$postfields = http_build_query($array);
		$status = curl_post($url,$postfields);
		print_r($status);
		//return $return;
	}

	/**
	 * @depends testPost
	 */
	public function testGet()
	{
		/*
		   $_COOKIE['session_id'] = $var['session_id'];
		   $var = $this->object->get(array());
		   $this->assertEquals("test",$var['session']['user_id']);
		 */
		// remove the following lines when you implement this test.
		//$this->marktestincomplete(
		//  'this test has not been implemented yet.'
		//);
		//return $var;
	}
	/**
	 * @depends testPOST
	 */
	public function testDelete($var)
	{
		/*
		   $this->object->delete(array("id"=>"test"));
		 */
		// remove the following lines when you implement this test.
		//$this->marktestincomplete(
		//  'this test has not been implemented yet.'
		//);
	}
	/**
	 * @covers Hello::getMessage
	 * @todo   Implement testGetMessage().
	 */
	public function testgetmessage()
	{
		// remove the following lines when you implement this test.
		//$this->marktestincomplete(
		//  'this test has not been implemented yet.'
		//);
	}
}
?>
