<?php
include_once("app/test/curl.php");
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-03-15 at 10:49:28.
 */
class accountsTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Hello
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testPost()
	{
//array($req['id'],$password,$req['email'],$req['role'],$req['url'],$req['about'],$icon));

		$url = "http://localhost/portfolio/accounts/";

		//$array = array("id"=>"test","password"=>"test","email"=>"foo@example.com","role"=>"admin","url"=>"www.example.com","about"=>"","icon"=>'@app/test/models/lena256.gif');
		$array = array("id"=>"test","password"=>"test","email"=>"foo@example.com","role"=>"admin");
		$postfields = http_build_query($array);
		$return = curl_post($url,$postfields);
		//print_r($return);
		//return $return;
	}

	/**
	 * @depends testPost
	 */
	public function testPut()
	{
		$url = "http://localhost/portfolio/accounts/test";

		$array = array("_method"=>"put","id"=>"test","password"=>"test","email"=>'foo@example.com',"role"=>"admin","url"=>"http://www.example.com","about"=>"","icon"=>'@app/test/models/lena256.gif');
		$return = curl_post($url,$array);
	}
	/**
	 * @depends testGet
	 */
	public function testGet()
	{
	}
	/**
	 * @depends testPOST
	 */
	public function testDelete($var)
	{
		/*
		   $this->object->delete(array("id"=>"test"));
		 */
		// remove the following lines when you implement this test.
		//$this->marktestincomplete(
		//  'this test has not been implemented yet.'
		//);
	}
	/**
	 * @covers Hello::getMessage
	 * @todo   Implement testGetMessage().
	 */
	public function testgetmessage()
	{
		// remove the following lines when you implement this test.
		//$this->marktestincomplete(
		//  'this test has not been implemented yet.'
		//);
	}
}
?>
